[project]
name = "html2md"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "argparse>=1.4.0",
    "beautifulsoup4>=4.12.3",
    "requests>=2.32.3",
]
